services:
  # PostgreSQL Database
  postgresql:
    image: postgres:15
    container_name: blog_postgresql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    networks:
      - blog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-blog_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: blog_redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    networks:
      - blog_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: blog_server
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - blog_network
      - proxy
    labels:
      - "traefik.enable=true"
      # API routes
      - "traefik.http.routers.blog-api.rule=Host(`muhammedtarikucar.com`,`www.muhammedtarikucar.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.blog-api.entrypoints=web,websecure"
      - "traefik.http.routers.blog-api.tls=true"
      - "traefik.http.routers.blog-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog-api.loadbalancer.server.port=5000"
      # Socket.IO
      - "traefik.http.routers.blog-socket.rule=Host(`muhammedtarikucar.com`,`www.muhammedtarikucar.com`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.blog-socket.entrypoints=web,websecure"
      - "traefik.http.routers.blog-socket.tls=true"
      - "traefik.http.routers.blog-socket.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog-socket.loadbalancer.server.port=5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${CLIENT_URL:-https://muhammedtarikucar.com}
    container_name: blog_client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - blog_network
      - proxy
    labels:
      - "traefik.enable=true"
      # Main site
      - "traefik.http.routers.blog.rule=Host(`muhammedtarikucar.com`,`www.muhammedtarikucar.com`)"
      - "traefik.http.routers.blog.entrypoints=web,websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=80"
      # Priority (API routes should have higher priority)
      - "traefik.http.routers.blog.priority=1"
      - "traefik.http.routers.blog-api.priority=10"
      - "traefik.http.routers.blog-socket.priority=10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backup service (optional)
  backup:
    image: postgres:15
    container_name: blog_backup
    restart: always
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-password123}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    command: /bin/bash -c "chmod +x /backup.sh && crond -f -d 8"
    depends_on:
      - postgresql
    networks:
      - blog_network
    profiles:
      - backup

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  blog_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
  proxy:
    external: true