version: '3.8'

services:
  # MongoDB for test environment
  mongodb-test:
    image: mongo:7.0
    container_name: muhammedtarikucar-mongodb-test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-testpassword123}
      MONGO_INITDB_DATABASE: muhammedtarikucar_test
    ports:
      - "27018:27017"  # Different port for test
    volumes:
      - mongodb_test_data:/data/db
      - mongodb_test_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - muhammedtarikucar-test-network
    command: mongod --auth
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API for test environment
  backend-test:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: muhammedtarikucar-backend-test
    restart: unless-stopped
    environment:
      NODE_ENV: test
      PORT: 5000
      MONGODB_URI: mongodb://admin:${MONGODB_ROOT_PASSWORD:-testpassword123}@mongodb-test:27017/muhammedtarikucar_test?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-test-jwt-secret-key-change-in-production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-test-jwt-refresh-secret-key-change-in-production}
      CORS_ORIGIN: http://test.muhammedtarikucar.com,http://localhost:3001
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 10485760
      ALLOWED_FILE_TYPES: jpg,jpeg,png,gif,webp
      RATE_LIMIT_WINDOW: 900000
      RATE_LIMIT_MAX: 100
      LOG_LEVEL: debug
      DOMAIN: test.muhammedtarikucar.com
    ports:
      - "5001:5000"  # Different external port for test
    volumes:
      - backend_test_uploads:/app/uploads
      - backend_test_logs:/app/logs
    networks:
      - muhammedtarikucar-test-network
    depends_on:
      mongodb-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend for test environment
  frontend-test:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://test.muhammedtarikucar.com/api
        VITE_SOCKET_URL: http://test.muhammedtarikucar.com
        VITE_ENVIRONMENT: test
    container_name: muhammedtarikucar-frontend-test
    restart: unless-stopped
    environment:
      NODE_ENV: test
      VITE_API_URL: http://test.muhammedtarikucar.com/api
      VITE_SOCKET_URL: http://test.muhammedtarikucar.com
      VITE_ENVIRONMENT: test
    ports:
      - "3001:80"  # Different external port for test
    networks:
      - muhammedtarikucar-test-network
    depends_on:
      backend-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis for test environment (optional, for caching and sessions)
  redis-test:
    image: redis:7.2-alpine
    container_name: muhammedtarikucar-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"  # Different port for test
    volumes:
      - redis_test_data:/data
    networks:
      - muhammedtarikucar-test-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-testredispassword}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_test_data:
    driver: local
    name: muhammedtarikucar_test_mongodb_data
  mongodb_test_config:
    driver: local
    name: muhammedtarikucar_test_mongodb_config
  backend_test_uploads:
    driver: local
    name: muhammedtarikucar_test_backend_uploads
  backend_test_logs:
    driver: local
    name: muhammedtarikucar_test_backend_logs
  redis_test_data:
    driver: local
    name: muhammedtarikucar_test_redis_data

networks:
  muhammedtarikucar-test-network:
    driver: bridge
    name: muhammedtarikucar-test-network
